
function lista = cube_nodes(m, n, l)
  %Dada una imagen (matriz) de m filas y n columnas, obtener una lista de los
  %elementos y los nodos correspondientes a cada elemento, empezando por abajo
  %a la derecha y siguiendo en orden antihorario.
  for h = 1:l
      for j = 1:n
          lista((j-1)*m+1+(h-1)*(m*n):j*m+(h-1)*(m*n), 1:9) = ...
              [((j-1)*m+1+(h-1)*(m*n):j*m+(h-1)*(m*n))', ...
              ((j-1)*(m+1)+1+(h-1)*((m+1)*(n+1)):j*(m+1)-1+(h-1)*((m+1)*(n+1)))', ...
              ((j-1)*(m+1)+2+(h-1)*((m+1)*(n+1)):j*(m+1)+(h-1)*((m+1)*(n+1)))', ...
              (j*(m+1)+1+(h-1)*((m+1)*(n+1)):(j+1)*(m+1)-1+(h-1)*((m+1)*(n+1)))', ...
              (j*(m+1)+2+(h-1)*((m+1)*(n+1)):(j+1)*(m+1)+(h-1)*((m+1)*(n+1)))', ...
              ((j-1)*(m+1)+1+h*((m+1)*(n+1)):j*(m+1)-1+h*((m+1)*(n+1)))', ...
              ((j-1)*(m+1)+2+h*((m+1)*(n+1)):j*(m+1)+h*((m+1)*(n+1)))', ...
              (j*(m+1)+1+h*((m+1)*(n+1)):(j+1)*(m+1)-1+h*((m+1)*(n+1)))', ...
              (j*(m+1)+2+h*((m+1)*(n+1)):(j+1)*(m+1)+h*((m+1)*(n+1)))'];
      end
  end
end
